services:
  deeprey-linux-os:
    hostname: deeprey-linux-os
    container_name: deeprey-linux-os
    image: deeprey-linux-os
    restart: unless-stopped
    build:
      context: dockerfiles/
      dockerfile: Dockerfile
    tty: true
    privileged: true # using loop devices
    volumes:
      - ../build/:/build
      - ../scripts:/scripts
      - ../onboard:/onboard
  deeprey-dev-os:
    hostname: deeprey-dev-os
    container_name: deeprey-dev-os
    image: deeprey-dev-os
    restart: unless-stopped
    build:
      context: dockerfiles/
      dockerfile: Dockerfile.dev
    tty: true
    privileged: true
    volumes:
      - ../../deeprey-gui:/deeprey-gui
      - ../../deeprey-radar:/deeprey-radar
      - ../../deeprey-sonar:/deeprey-sonar
      - ../../deeprey-navbar:/deeprey-navbar
      - ./..:/deeprey-linux-os
      - ../../OpenCPN:/OpenCPN
      - ../../onboard:/onboard
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      - DISPLAY=${DISPLAY}
      - OPENCPN_SRC_DIR=/OpenCPN
      - DEEPREY_GUI_SRC_DIR=/deeprey-gui
    devices:
      - /dev/dri
    stdin_open: true

